### ISSUE TITLE
Error setting up PG trigger

### ISSUE THREAD

**Issue by adampash** [cheerfulstoic/ecto_watch#10]
I'm running into a strange problem setting up ecto_watch on a new project:

```
** (EXIT) an exception was raised:
                ** (Postgrex.Error) ERROR 42601 (syntax_error) syntax error at or near "TRIGGER"

    query: CREATE OR REPLACE TRIGGER ew_inserted_for_aboardex_repo_transaction_trigger
  AFTER INSERT ON "app_public"."transactions" FOR EACH ROW
  EXECUTE PROCEDURE "app_public".ew_inserted_for_aboardex_repo_transaction_func();

                    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
                    (ecto_watch 0.5.3) lib/ecto_watch/watcher_server.ex:100: EctoWatch.WatcherServer.init/1
                    (stdlib 5.2) gen_server.erl:980: :gen_server.init_it/2
                    (stdlib 5.2) gen_server.erl:935: :gen_server.init_it/6
                    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

I've used this on another project without issue, but for some reason I'm getting this here. My best guess here is that `CREATE OR REPLACE TRIGGER` is not valid in older versions of Postgres (e.g., PG 12, which is where this is failing). In newer versions, it works. 

The simplest solution is probably to change the following:

https://github.com/cheerfulstoic/ecto_watch/blob/825bfbe969d820982423cd96b634d28a375adb8f/lib/ecto_watch/watcher_server.ex#L103

to:

```sql
DROP TRIGGER IF EXISTS #{unique_label}_trigger on \"#{schema_name}\".\"#{table_name}\";
```

followed by:

```sql
CREATE TRIGGER #{unique_label}_trigger -- etc...
```

I'm happy to PR if it's helpful.

**Comment by cheerfulstoic** [comment]
Thanks for reporting this, good to know!  Looks like `OR REPLACE` was added to postgres in [13.3.4](https://www.postgresql.org/docs/14/release-14.html)

Just released your proposed fix as 0.5.4, so let me know if that works or not 👍

**Comment by adampash** [comment]
That works! Thanks so much, appreciate the quick fix.

**Comment by cheerfulstoic** [comment]
FYI there's a new change in version 0.14.0 which automatically switches between these two based on the version of the postgres server that you're connecting to.  It shouldn't change anything for you, but just wanted to update this issue so that you know. See #55 and #50
