### ISSUE TITLE
Missing unsubscribe functionality

### ISSUE THREAD

**Issue by nelsonmestevao** [cheerfulstoic/ecto_watch#33]
I was looking for unsubscribing a specified record by its ID. However, it does not seem that EctoWatch exposes such functionality. Is that on purpose?

**Comment by cheerfulstoic** [comment]
That's a good idea!  I'd be happy to look into this a bit later (after CodeBEAM), but I'd also welcome a PR ❤️

**Comment by nelsonmestevao** [comment]
Awesome, thank you :bow: I open a PR https://github.com/cheerfulstoic/ecto_watch/pull/34 :muscle:
